# Generated by Django 2.1.7 on 2019-03-21 09:32

from django.db import migrations
import ei.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=ei.models.ei_image_path),
        ),
    ]
